<a href="https://colab.research.google.com/github/tasnim0tantawi/deep-learning-PyTorch/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
import torch
tensor1 = torch.randn(size=(7,7))
tensor2 = torch.randn(size=(1,7))

tensor1, tensor2




(tensor([[ 1.3856, -0.6998,  1.3270, -0.3333, -0.7711, -0.1156, -0.5781],
         [ 0.2077,  0.4938,  1.7203,  0.3133, -1.2446, -0.8080,  1.0435],
         [-0.3934, -0.5741,  0.3203,  0.1616,  0.9256, -0.2249, -0.4807],
         [ 1.5990,  0.4099, -2.3027, -1.3561,  0.1101,  1.2703,  1.3122],
         [-0.9229,  0.4294,  0.4444, -1.1751, -1.0308, -0.7591, -0.2647],
         [ 2.4324,  1.0683,  0.1428,  0.1014, -1.2074,  0.2386,  0.8159],
         [ 0.9025,  0.8917, -0.1011, -1.2106,  1.9003, -0.2835,  0.8151]]),
 tensor([[ 0.6821, -1.8012,  0.2614,  0.9443,  1.6396,  3.3392, -0.3040]]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Perform matrix multiplication 
mul = tensor1 @ tensor2.T 
mul2 = torch.matmul(tensor1, tensor2.T)
print(mul, mul2)

tensor([[ 0.7634],
        [-5.0583],
        [ 1.9148],
        [ 2.4931],
        [-6.5408],
        [-1.5631],
        [-0.2386]]) tensor([[ 0.7634],
        [-5.0583],
        [ 1.9148],
        [ 2.4931],
        [-6.5408],
        [-1.5631],
        [-0.2386]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [8]:
# Set manual seed
SEED = 0

torch.manual_seed(seed=SEED)
tensor1 = torch.randn(size=(7, 7))

torch.manual_seed(seed=SEED)
tensor2 = torch.randn(size=(7, 7))
print(tensor1==tensor2)
print(tensor1 @ tensor2)



tensor([[True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True]])
tensor([[ 4.9215,  1.2452,  2.2888,  0.2346, -2.5678,  0.0165,  0.5293],
        [ 2.0765,  7.4165,  0.8298,  1.7133, -0.6009, -2.8773, -0.8510],
        [ 2.2317,  2.3053, -1.9719, -0.3354,  1.5266,  0.2913, -1.3854],
        [ 2.8104,  0.7046, -1.0625, -1.8512, -0.0526, -0.4246,  0.3262],
        [-1.6429,  1.3891, -7.7341, -2.5960,  4.6502,  1.1105,  0.5393],
        [-0.3762,  1.4955,  0.1894,  0.4410,  1.0550, -1.0226, -1.7264],
        [-8.3027, -1.3600, -0.9380,  2.0054, -1.1136,  2.6662,  5.8636]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [9]:
# Set random seed on the GPU
device = "cuda" if torch.cuda.is_available() else "CPU"
device




'cuda'


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [23]:
# Set random seed
torch.manual_seed(1234)
tensor3 = torch.rand(2, 3).to(device=device)

torch.manual_seed(1234)
tensor4 = torch.rand(2, 3).to(device=device)
print(tensor3.device, tensor4.device)
print(tensor3==tensor4)


cuda:0 cuda:0
tensor([[True, True, True],
        [True, True, True]], device='cuda:0')


In [22]:
!nvidia-smi


Tue Jan 31 01:10:30 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P0    27W /  70W |    794MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [25]:
# Perform matmul on tensor_A and tensor_B
output =torch.matmul(tensor3, tensor4.T)
print(output)

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [19]:
# Find max
print(output.max())
print(torch.max(output))


# Find min
print(output.min())
print(torch.min(output))


tensor(0.7597, device='cuda:0')
tensor(0.7597, device='cuda:0')
tensor(0.0031, device='cuda:0')
tensor(0.0031, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [21]:
# Find arg max
print(output.argmax())


# Find arg min
print(output.argmin())



tensor(7, device='cuda:0')
tensor(2, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [26]:
torch.manual_seed(1234)
tensor5= torch.rand(1, 1, 1, 10)

tensor6= tensor5.squeeze()
print(tensor5)
print(tensor5.shape)

print(tensor6)
print(tensor6.shape)





tensor([[[[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681,
           0.6738, 0.3315]]]])
torch.Size([1, 1, 1, 10])
tensor([0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681, 0.6738,
        0.3315])
torch.Size([10])
